version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
